### ISSUE TITLE
Docker builds are not working

### ISSUE THREAD

**Issue by thirtythreeforty** [thirtythreeforty/neolink#104]
Looks like something changed upstream and [recent Docker builds are not working](https://github.com/thirtythreeforty/neolink/runs/1518580553):
```
error: linking with `cc` failed: exit code: 1
  |
  = note: /usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: /usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../lib/libgstrtspserver-1.0.so: undefined reference to `gst_rtsp_connection_set_content_length_limit'
```

**Comment by QuantumEntangledAndy** [comment]
The function `gst_rtsp_connection_set_content_length_limit` is [here](https://github.com/sdroege/gstreamer-sys/blob/80eb584a7a527eb98a65918a1ce0b81c07780529/gstreamer-rtsp-sys/src/lib.rs#L951-L955) 

```rust
#[cfg(any(feature = "v1_18", feature = "dox"))]
    pub fn gst_rtsp_connection_set_content_length_limit(
        conn: *mut GstRTSPConnection,
        limit: c_uint,
    );
```

and it is supposed to be behind the `"v1_18"` feature. I think we need to pin the feature set to the minimum required for neolink.

```toml
gstreamer = { version = "0.16", features = ["v1_14"]}
gstreamer-app = { version = "0.16", features = ["v1_14"]}
gstreamer-rtsp = { version = "0.16", features = ["v1_14"]}
gstreamer-rtsp-server = { version = "0.16", features = ["v1_14"]}
```

I am running a build with this now to test
