### ISSUE TITLE
reolink e1 camera rtsp stream only show audio but not video

### ISSUE THREAD

**Issue by saarsinai** [thirtythreeforty/neolink#156]
**Describe the bug**
configured the docker container next to my other container.
```
  neolink:
    hostname: neolink
    container_name: neolink
    image: thirtythreeforty/neolink
    restart: unless-stopped
    ports:
      - 8554:8554
    volumes:
      - ${USERDIR}/config/neolink/config.toml:/etc/neolink.toml
```

in the logs i can see that it's connected to the camera.
but when i use the rtsp url using vlc to see if it works, all i can hear is tha audio, no video.
also tried to add it to my nvr system and did not work as well.

reolink e1 (not pro)
firmware version: v3.0.0.115_20102200
hardware version: IPC_517SD5

the toml file:

```
bind = "0.0.0.0"

[[cameras]]
name = "garden"
format = "h264"
username = "admin"
password = "HIDDEN"
address = "192.168.1.120:9000"
stream = "both"
```
