### ISSUE TITLE
Docker Compose directory error

### ISSUE THREAD

**Issue by NWalledge** [thirtythreeforty/neolink#275]
**Describe the bug**

root@Neolink:/# docker-compose up
Starting e1ba3a1f7135_neolink ... done
Attaching to e1ba3a1f7135_neolink
e1ba3a1f7135_neolink | [2022-05-19T10:09:55Z INFO  neolink] Neolink 0.4.0 (unknown commit) release
e1ba3a1f7135_neolink | Error: Failed to read "/etc/neolink.toml"
e1ba3a1f7135_neolink | 
e1ba3a1f7135_neolink | Caused by:
e1ba3a1f7135_neolink |     Is a directory (os error 21)
root@Neolink:/# ^C

Currently getting this error

**To Reproduce**
Steps to reproduce the behavior. Example:
Create Neolink docker-compose
Start docker-compose

**Expected behavior**
It to work

**Versions**
NVR software:
Neolink software:
Reolink camera model and firmware:

**Comment by QuantumEntangledAndy** [comment]
You need to provide it with a config file mounted in the right place. There's an example config file in the repo.

**Comment by abstract-entity** [comment]
In the docker-compose file you've set a w rong local file path: 

```
version: "2"
services:
  neolink:
    image: thirtythreeforty/neolink
    container_name: neolink
    ports:
      - 8554:8554
    volumes:
      - >>>WRITE HERE THE PATH TO YOUR CONFIGON YOUR LOCAL MACHINE<<<:/etc/neolink.toml
    restart: unless-stopped
```
