### ISSUE TITLE
Motion based stream settings not working (Argus Eco)

### ISSUE THREAD

**Issue by blipk** [thirtythreeforty/neolink#325]
**Describe the bug**
I've set up a config with the below settings in reference from the comment in the PR #210 
```toml
bind = "0.0.0.0"

[[users]]
name = "myuser"
pass = "mypass"

[[cameras]]
name = "cam"
username = "user"
password = "pass"
uid = "myuid"
  [cameras.pause]
  on_motion = true
  on_client = false
  mode = "black"
  timeout = 1.0
```
Running with `neolink rtsp --config config.toml`
I have placed the camera next to a wall with no motion, however it continues to stream (accessing stream via RTSP in VLC).
"PIR Motion Sensor" is enabled in the Reolink app, and there is no available firmware updates.

**Expected behavior**
For a black stream when there is no motion

**Versions**
NVR software: None
Neolink software: Artifcat from CI build here: https://github.com/thirtythreeforty/neolink/actions/runs/3064348245
Reolink camera model and firmware:
Argus Eco 1109_730_107_481

Please let me know if you require any additional debug information or files.
