### ISSUE TITLE
ffmpeg missing picture in access unit with size

### ISSUE THREAD

**Issue by ternium1** [thirtythreeforty/neolink#338]
**Describe the bug**
Error when trying to stream the main channel of a camera (B800), no issues with the substream.
FFmpeg crashes with `missing picture in access unit with size 88` on multiple ffmpeg clients
VLC stream works fine though 

**To Reproduce**
Steps to reproduce the behavior. Example:
1. Create this configuration file:
```toml
[[cameras]]
name = "parking"
username = "admin"
password = "xxxxxxxxxx"
address = "10.21.0.16:9000"
```
3. Launch Neolink via docker-compose
4. execute ffprobe and ffmpeg with different arguments
I saw multiple issues with similar problems, but none of them helped me fix this error
**Expected behavior**
FFMPEG should work fine even on the main stream

**Versions**
NVR software: frigate/ffmpeg
Neolink software: lastest docker image (Neolink 0.4.0)
Reolink camera model and firmware: B800 v3.0.0.183_21012800
