### ISSUE TITLE
Talk via HomeAssistant Frigate hass-card microphone.

### ISSUE THREAD

**Issue by Joeviocoe** [thirtythreeforty/neolink#389]
I'm using Neolink talk command with a non-doorbell reolink camera. This test command works, `ffmpeg -i https://rhasspy.github.io/piper-samples/samples/en/en_US/lessac/high/speaker_0.mp3 -f  alaw -ar 8000 -f wav - | ./neolink talk front_door -c config.toml --volume=1.0 -m -i "fdsrc fd=0"` as I can hear the camera speak the arbitrary audio file.  Two-way audio does work with this camera using the official Reolink mobile app.  So I would think that Neolink should be able to do this too.

I am running Home Assistant (supervised with docker) with the Frigate and Neolink addons.  (_I still need to find out how to have ffmpeg/gstreamer preloaded and persistent across docker/addon restarts_).

But I am now trying to get my frigate hass card with the microphone button working.
I'm on the HomeAssistant Android app, and pressing the microphone button highlights it red, I speak into the phone mic, but no sound comes out of the camera speaker.

```
go2rtc:
  streams:
    cam_backyard:
      - "ffmpeg:http://10.0.x.x/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=admin&password=PASS#video=copy#audio=copy#audio=opus"
      - rtsp://admin:PASS@10.0.x.x/Preview_01_main
    cam_backyard_sub:
      - rtsp://admin:PASS@10.0.x.x/Preview_01_sub
      - exec:/config/neolink/neolink_talk.sh#backchannel=1
      
cameras:
  cam_backyard:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam_backyard
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/cam_backyard_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
  ```
  
 /config/neolink/neolink_talk.sh -->
```
#!/usr/bin/env bash

ffmpeg -fflags nobuffer -f alaw -ar 8000 -i - -f wav - | /config/neolink/neolink talk Driveway -c config.toml --volume=1.0 -m -i "fdsrc fd=0"
```
  
  I am looking for documentation, tutorial or guide that describes how it is "supposed to work" with a Reolink camera.
