### ISSUE TITLE
addon/plugin/costume component For Home Assistant

### ISSUE THREAD

**Issue by thirtythreeforty** [thirtythreeforty/neolink#45]
Migrated from #44:

> Hello All
> 
> It's possible to create a addon/plugin/costume component based in neolink to running in HA -Home Assistant
> 
> I think this can be useful once we can integrate the reolink cameras that is not supporting the RTSP or ONVIF protocols.
> 
> Converting in a supported devices to be available :)
> 
> Think about this please
> 
> Best regards

**Comment by thirtythreeforty** [comment]
@nunokaneco thanks for the request. I don't know much about Home Assistant. If you have a specific description about how it should be integrated, I'm open to facilitating, but I don't think I'll be able to personally work on HA integration.

**Comment by QuantumEntangledAndy** [comment]
I use homeassistant with neolink. Adding the following in the config as a genertic ffmpeg camera should work:

```
camera:
  - platform: ffmpeg
    name: Living Room Live
    input: -rtsp_transport tcp -probesize 500 -i rtsp://<NEOLINKIP>:8554/<NAME_CAM>
```
